# Generated by Django 3.1.12 on 2024-11-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20241130_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
