# Generated by Django 5.1.3 on 2024-12-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
